spring.application.name=demo
# Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1105
# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# JWT
app.jwt.secret=demo-jwt-secret-key-please-change-in-production-2026
app.jwt.exp-minutes=1440
